config/routes.rb
Rails.application.routes.draw do



  ########################################################################################################
  
  namespace :dashboard do
    
    controller :pages do
      get '/home' => :home
    end
  	
  	controller :users do
  	end
    resources :users

    root 'pages#home'
    get '*path' => redirect('/')
  end

  ########################################################################################################

  devise_for :users

  controller :pages do
    get '/home' => :home
    get '/reserva' => :reserva
  end

  controller :users do
    post "users/novo_contato" => :novo_contato
  end
  
  controller :events do
    get "events/nova_reserva" => :nova_reserva
    post "events/cancelar/:id" => :cancelar, as: :events_cancelar
  end
  resources :events
    

  root "pages#home"
  get '*path' => redirect('/')
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	validates_presence_of :event_date, :event_time, :people

	belongs_to :user

	def cancelar!
		self.update(canceled: true)
	end

end

app/models/location.rb
class Location < ApplicationRecord
    acts_as_mappable :default_units => :miles, :default_formula => :sphere, :distance_field_name => :distance, :lat_column_name => :lat, :lng_column_name => :lng

    def self.address address
        return "#{address[:address]}, #{address[:neighborhood]}, #{address[:city]} - #{address[:state]} - #{address[:zipcode]}"
    end
end

=begin
address => {:neighborhood=>"Cavaleiro", :zipcode=>"54250610", :city=>"Jaboatão dos Guararapes", :address=>"Rua Fernando Amorim", :state=>"PE", :complement=>""}
=end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")

  # When config/app.yml has changed, you need change this prefix to v2, v3 ... to expires caches
  # cache_prefix { "v1" }

  def self.animated
  	"show-off #{['fadein', 'slidein'].sample}#{['up', 'down', 'left', 'right'].sample}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	validates_presence_of :phone
	validates_presence_of :name

  has_many :events, dependent: :destroy
  accepts_nested_attributes_for :events,  allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id


    begin
      a = params[:event][:event_date].to_date
    rescue Exception => @erro
    end


    @event.save
    @event.errors.messages[:erro] = ["#{@erro}"] unless @erro.blank?
    respond_to do |format|
      format.js  
    end

  end

  def update
    begin
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      respond_to do |format|
        format.js {render inline: "M.toast({html: '#{e.message}', classes: 'red'}); " }
      end
    end
    @event.update(event_params)
    respond_to do |format|
      format.js  
    end
  end

  def cancelar
    begin
      @event = Event.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      respond_to do |format|
        format.js {render inline: "M.toast({html: '#{e.message}', classes: 'red'}); " }
      end
    end
    if @event.cancelar!
      redirect_to request.referrer, alert: "Evento cancelado"
    else
      respond_to do |format|
        format.js {render inline: "M.toast({html: '#{@event.errors.full_messages.first}', classes: 'red'}); " }
      end
    end

  end

  def nova_reserva
    @event = params[:id].blank? ? Event.new : Event.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_date, :event_time, :people, :message, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@images = Dir.glob("public/images/banners/*.jpg")
		@examples = Dir.glob("public/images/examples/*.jpg")

  end

  def reserva
  	current_user.blank? ? @user = User.new : @event = Event.new(user_id: current_user.id)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def novo_contato
    u = User.new(user_params)
    u.user_agent = request.env['HTTP_USER_AGENT']
    u.remote_ip = request.remote_ip
    u.password = Devise.friendly_token
    l = Location.geocode(Rails.env.development? ? '179.154.141.205' : u.remote_ip)
    u.location = l.to_json unless l.blank?


    @user = User.find_or_create_by(email: u.email) do |user|
      user.name = u.name
      user.password = u.password
      user.phone = u.phone
      user.user_agent = u.user_agent
      user.remote_ip = u.remote_ip
      user.location = u.location
    end

    if @user.valid?
      sign_in(:user, @user)
      redirect_to request.referrer, notice: "Salvo!"
    else
      respond_to do |format|
        format.js  
      end
    end





  #@user.errors.messages[:erro] = ["#{@erro}"] unless @erro.blank?
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :phone, 
                                  events_attributes: [:id, :event_date, :event_time, :people])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
	def meus_eventos_ativos user = current_user
		if user.blank?
			return nil
		else
			user.events.where("events.event_date > '#{Date.yesterday}'")
		end
	end

	def event_status(event)
		if event.canceled
			return "<span class='span red-text'>Cancelado</span>".html_safe
		elsif event.confirmed
			return "<span class='span green-text'>Confirmado</span>".html_safe
		else
			return "<span class='span orange-text'>Aguardando...</span>".html_safe
		end
	end

end

app/views/events/_form.html.erb
<%= form_for [@event], remote: true do |f| %>
	
	<div id="form_error"></div>

	
	<div class="field">
		<div class="input-field col s12 m12 l12">
			<i class="material-icons prefix">date_range</i>
			<%= f.text_field :event_date, 'data-toggle' => 'datepicker', :onkeypress => "mascara(this, checaData)", maxlength: 10 %>
			<div data-toggle="datepicker"></div>
			<label for="event_event_date">Data do Evento</label>
		</div>
	</div>
	<div class="field">
		<div class="input-field col s12 m12 l12">
			<i class="material-icons prefix">timer</i>
			<%= f.text_field :event_time, :onkeypress => "mascara(this, checaNumero)", maxlength: 2  %>
			<label for="event_event_time">Horário do início do Evento</label>
		</div>
	</div>
	<div class="field">
		<div class="input-field col s12 m12 l12">
			<i class="material-icons prefix">people</i>
			<%= f.text_field :people, :onkeypress => "mascara(this, checaNumero)", maxlength: 3  %>
			<label for="event_people">Convidados</label>
		</div>
	</div>
	<div class="field">
		<div class="input-field col s12 m12 l12">
			<i class="material-icons prefix">message</i>
			<%= f.text_field :message  %>
			<label for="event_message">Mensagem</label>
		</div>
	</div>
	<div class="actions">
		<button class="btn blue right darken-2 waves-effect waves-light" type="submit" name="action">
			<i class="material-icons">send</i>
		</button>
	</div>
<% end %>

<script type="text/javascript">
	$("input").blur(function(){
		if ($(this).val() == ""){
			$(this).css("border-bottom","1px solid red");
		}else{
			$(this).css("border-bottom","1px solid green");
		}
	});
	$("input#event_event_date").change(function(){
  		M.updateTextFields();
	});1
</script>

app/views/events/_list.html.erb
<p>
  <%= link_to "Nova reserva", events_nova_reserva_path, class: "btn shadow green peso-4", remote: true  %>
</p>
<br>
<div class="overflow">
  <table class="f15">
    <thead>
      <tr>
        <th>Evento</th>
        <th>Data</th>
        <th>Convidados</th>
        <th>Status</th>
        <th>#</th>
      </tr>
    </thead>

    <tbody>
      <% meus_eventos_ativos.each do |evento| %>
        <tr class="<%= 'grey lighten-2' if evento.canceled %>">
          <td><%= evento.id %></td>
          <td><%= "#{l evento.event_date, format: :long} às #{evento.event_time} horas" %></td>
          <td><%= evento.people %></td>
          <td><%= event_status(evento) %></td>
          <td>
            <% unless evento.canceled %>
              <%= link_to events_nova_reserva_path(id: evento.id), remote: true do %>
                <i class="material-icons blue-text" style="font-size: 1.5rem;">edit</i>
              <% end %>
              <%= link_to events_cancelar_path(evento), method: "post" do %>
                <i class="material-icons red-text" style="font-size: 1.5rem;">cancel</i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/create.js.erb
<% if @event.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @event )%>");
  $('html, body').animate({
  	scrollTop: $("#form_error").offset().top
  }, 500);

	<% @event.errors.full_messages.each do |msg| %>
		<% if msg.include?"" %>
			$("#event_event_date").css("border-bottom","1px solid red");
		<% elsif msg.include?"Email" %>
			$("#event_event_time").css("border-bottom","1px solid red");
		<% elsif msg.include?"Name" %>
			$("#event_people").css("border-bottom","1px solid red");
		<% end %>
	<% end %>

<% else %>
  $("#new_event").html("<%= j( render '/shared/form_success', object: @event )%>");
<% end %>

app/views/events/nova_reserva.js.erb
$("#content").hide().html("<%= j( render '/events/form' )%>").fadeIn("slow");

$('[data-toggle="datepicker"]').datepicker({
	language: 'pt-BR'
}); 

M.updateTextFields();

app/views/events/update.js.erb
<% if @event.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @event )%>");
  $('html, body').animate({
  	scrollTop: $("#form_error").offset().top
  }, 500);

	<% @event.errors.full_messages.each do |msg| %>
		<% if msg.include?"" %>
			$("#event_event_date").css("border-bottom","1px solid red");
		<% elsif msg.include?"Email" %>
			$("#event_event_time").css("border-bottom","1px solid red");
		<% elsif msg.include?"Name" %>
			$("#event_people").css("border-bottom","1px solid red");
		<% end %>
	<% end %>

<% else %>
  $("#edit_event_<%= @event.id %>").html("<%= j( render '/shared/form_success', object: @event )%>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>San Carlo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes"></head>
  </head>

  <body class="<%= controller_name %> <%= action_name %> public">
    <main>
      <header>
        <%= render "/shared/navbar" %>
      </header>
      <%= yield %>
      <footer class="no-margin">
        <%= render "/shared/footer" %>
      </footer>
    </main>
    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'red'})" %>
      <% elsif message_type == 'notice' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'green'})" %>
      <% elsif message_type == 'info' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'blue'})" %>
      <% elsif message_type == 'warning' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'orange'})" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>San Carlo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes"></head>
  </head>

  <body class="<%= controller_name %> <%= action_name %> public">
    <main>
      <%= yield %>
    </main>
    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'red'})" %>
      <% elsif message_type == 'notice' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'green'})" %>
      <% elsif message_type == 'info' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'blue'})" %>
      <% elsif message_type == 'warning' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'orange'})" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home_content">
	<div class="banner animated lightSpeedIn slow">
		<%= render "/shared/carousel", images: @images %>
	</div>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_bottom", color: "#ECE9E4", margin: "-77px;" %>
		</div>
	</section>
	<div class="sancarlo">
		<div class="container">
			<br>
			<h4 class="green-text text-darken-2 center <%= Setting.animated %>">San Carlo</h4>
				<p class="span f18 <%= Setting.animated %>">
					Somos uma empresa focada e especializada em festas. Visão profissional, atendimento personalizado, e apresentação de soluções completas e adequadas ao melhor custo benefício conquistam nossos clientes a cada evento realizado. Flexibilidade e integridade, sempre considerando os interesses do cliente, são nossos principais valores e diferenciais. Realizar eventos com comprometimento, seriedade e organização fazem de nós facilitadores de um mundo de sonhos que vão de encontro à realidade. Quantos sonhos realizados! Quantas emoções nos mais variados rostos! Sentimentos que marcam vidas e que fazem nossa história!.
				</p>
				<p class="span f18 <%= Setting.animated %>">
					Nosso grande desafio é tornar seu sonho mais real do que do que você imagina. Planejamos e executamos o seu evento otimizando os recursos e minimizando os custos.
				</p>
			<br>
			<br>



		</div>
	</div>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_top", color: "#ECE9E4", margin: "0;" %>
		</div>
	</section>

	<div class="salao">
		<div class="container">
			<br>
			<h4 class="green-text text-darken-2 center <%= Setting.animated %>">Salão</h4>
			<br>
            <div class="row">
            	<div class="col s12 m12 l6">
			<div class="slider slider-single">
				<% @examples.each do |image| %>
					<div><img src="<%= image.gsub('public','') %>" style="width: 100%; height: auto;"></div>
				<% end %>
			</div>
			<div class="slider slider-nav" style="max-height: 100px;">
				<% @examples.each do |image| %>
					<div><img src="<%= image.gsub('public','') %>" style="width: 64px; height: 64px;"></div>
				<% end %>
			</div>

            	</div>
            	<div class="col s12 m12 l5 offset-l1">
        			<p class="span f18 <%= Setting.animated %>">
						O San Carlo Festas e Eventos é projetado especialmente para oferecer eventos deslumbrantes e inesquecíveis. Sua arquitetura moderna, inovadora e estruturada permite além do bem estar, uma imagem marcante do local proporcionando as melhores recordações de foto e filmagem. O local oferece excelente conforto e comodidade, ingredientes essenciais para que seu evento seja um sucesso.
        			</p>
            	</div>
            </div>
            <br>
		</div>
	</div>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_bottom", color: "#ff7043", margin: "-77px;" %>
		</div>
	</section>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_top", color: "#ff7043", margin: "0;" %>
		</div>
	</section>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_bottom", color: "rgba(255, 255, 255, 0.2)", margin: "-77px;" %>
		</div>
	</section>

	<div id="types" class="types">
		<div class="container">
			<br>
			<h4 class="green-text text-darken-2 center <%= Setting.animated %>">Tipos de Eventos</h4>
			<p class="span f18 <%= Setting.animated %>">
				Somos uma empresa focada e especializada em festas. Visão profissional, atendimento personalizado, e apresentação de soluções completas e adequadas ao melhor custo benefício conquistam nossos clientes a cada evento realizado. Flexibilidade e integridade, sempre considerando os interesses do cliente, são nossos principais valores e diferenciais. Realizar eventos com comprometimento, seriedade e organização fazem de nós facilitadores de um mundo de sonhos que vão de encontro à realidade. Quantos sonhos realizados! Quantas emoções nos mais variados rostos! Sentimentos que marcam vidas e que fazem nossa história!.
			</p>
			<p class="span f18 <%= Setting.animated %>">
				Nosso grande desafio é tornar seu sonho mais real do que do que você imagina. Planejamos e executamos o seu evento otimizando os recursos e minimizando os custos.
			</p>
		</div>
	</div>
	
	<br>
	<br>

	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_bottom", color: "#a1887f", margin: "-77px;" %>
		</div>
	</section>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_top", color: "#a1887f", margin: "0;" %>
		</div>
	</section>
	<section class="wave" style="position: relative; height: 50px;">
		<div class="waver_bottom">
			<%= render "/shared/waver_bottom", color: "rgba(255, 255, 255, 0.5)", margin: "-57px;" %>
		</div>
	</section>

	<div id="services" class="services">
		<div class="container">
			<br>
			<h4 class="green-text text-darken-2 center <%= Setting.animated %>">Serviços</h4>
			<p class="span f18 <%= Setting.animated %>">
				Somos uma empresa focada e especializada em festas. Visão profissional, atendimento personalizado, e apresentação de soluções completas e adequadas ao melhor custo benefício conquistam nossos clientes a cada evento realizado. Flexibilidade e integridade, sempre considerando os interesses do cliente, são nossos principais valores e diferenciais. Realizar eventos com comprometimento, seriedade e organização fazem de nós facilitadores de um mundo de sonhos que vão de encontro à realidade. Quantos sonhos realizados! Quantas emoções nos mais variados rostos! Sentimentos que marcam vidas e que fazem nossa história!.
			</p>
			<p class="span f18 <%= Setting.animated %>">
				Nosso grande desafio é tornar seu sonho mais real do que do que você imagina. Planejamos e executamos o seu evento otimizando os recursos e minimizando os custos.
			</p>
		</div>
	</div>

</div>



<script type="text/javascript">
 $('.slider-single').slick({
 	slidesToShow: 1,
 	slidesToScroll: 1,
 	arrows: true,
 	fade: false,
 	adaptiveHeight: true,
 	infinite: false,
	useTransform: true,
 	speed: 400,
 	cssEase: 'cubic-bezier(0.77, 0, 0.18, 1)',
 });

 $('.slider-nav')
 	.on('init', function(event, slick) {
 		$('.slider-nav .slick-slide.slick-current').addClass('is-active');
 	})
 	.slick({
 		slidesToShow: 7,
 		slidesToScroll: 7,
 		dots: false,
 		focusOnSelect: false,
 		infinite: false,
 		responsive: [{
 			breakpoint: 1024,
 			settings: {
 				slidesToShow: 5,
 				slidesToScroll: 5,
 			}
 		}, {
 			breakpoint: 640,
 			settings: {
 				slidesToShow: 4,
 				slidesToScroll: 4,
			}
 		}, {
 			breakpoint: 420,
 			settings: {
 				slidesToShow: 3,
 				slidesToScroll: 3,
		}
 		}]
 	});

 $('.slider-single').on('afterChange', function(event, slick, currentSlide) {
 	$('.slider-nav').slick('slickGoTo', currentSlide);
 	var currrentNavSlideElem = '.slider-nav .slick-slide[data-slick-index="' + currentSlide + '"]';
 	$('.slider-nav .slick-slide.is-active').removeClass('is-active');
 	$(currrentNavSlideElem).addClass('is-active');
 });

 $('.slider-nav').on('click', '.slick-slide', function(event) {
 	var goToSingleSlide = $(this).data('slick-index');

 	$('.slider-single').slick('slickGoTo', goToSingleSlide);
 });
</script>

app/views/pages/reserva.html.erb
<div id="reserva_content">
	<div class="container">
		<div class="lead">
			<h5 class="white-text peso-6 center">
				Gostaria de fazer uma reserva conosco? 
			</h5>
			<div class="row">
				<div class="col s12 m10 l10 offset-m1 offset-l1">
					<div class="card">
						<div class="card-content">
							<span id="content" class="card-title activator blue-text text-darken-2">
								<% if current_user.blank? %>
									Preencha o formulário com os dados:
									<%= render "/users/form" %>
								<% elsif meus_eventos_ativos.blank? %>
									<span class="span blue-text text-darken-2 f18">
										<%= "#{current_user.name.humanize}".split(/ /).first %> preencha as informações sobre o evento:
									</span>
									<%= render "/events/form" %>
								<% else %>
									<%= render "/events/list" %>
								<% end %>
							</span>
							<br>
							&nbsp;
						</div>
						<div class="card-action">
							<%= link_to "meus eventos", reserva_path, class: "blue-text text-lighten-2" unless meus_eventos_ativos.blank? %>
							<%= link_to "sair", destroy_user_session_path, :method => :delete, class: "blue-text text-lighten-2" unless current_user.blank? %>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>


<style type="text/css">
	footer{
		background: #d7ccc8;
	}
</style>

app/views/shared/_carousel.html.erb
<div class="main-slider">
  <% images.each_with_index do |image, index| %>
    <div class="t-slide  <%= 'current-t-slide' if index == 0 %>">
      <img src="<%= image.gsub('public','') %>" alt="" />
    </div>
  <% end %>

  <div class="t-slider-controls ">
    <div class="arrow right-arrow" style="z-index: 3;">
      <div class="arrow-container">
        <div class="arrow-icon"><i class="material-icons green-text text-darken-3">arrow_forward</i></div>
      </div>
    </div>
    <div class="arrow left-arrow" style="z-index: 3;">
      <div class="arrow-container">
        <div class="arrow-icon"><i class="material-icons green-text">arrow_back</i></div>
      </div>
    </div>
    <div class="t-load-bar">
      <div class="inner-load-bar"></div>
    </div>
    <div class="t-dots-container">
      <div class="t-slide-dots-wrap">
        <div class="t-slide-dots">

        </div>
      </div>
    </div>
  </div>
  <div class="third-slider text-slider">
  </div>
</div>

app/views/shared/_footer.html.erb
<section class="wave" style="position: relative; height: 100px;">
  <div class="waver_bottom">
    <%= render "/shared/waver_bottom", color: "#a1887f", margin: "0;" %>
  </div>
</section>
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Contato</h5><br>
        <h5 class="white-text">Localização</h5>


      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">WhatsApp</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">YouTube</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" style="background: #a1887f;">
    <div class="container center">
    © 2019 Copyright San Carlo
    </div>
  </div>
</footer>

app/views/shared/_form_error.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content white-text">
          <span class="card-title red-text">OPS <span class="badge red white-text"><%= object.class.to_s == "User" ? (object.errors.size-1) : object.errors.size %></span></span>
          <% object.errors.full_messages.each do |msg| %>
          <% msg = msg.gsub("Name","Nome") %>
          <% msg = msg.gsub("Phone","Fone") %>
          <% msg = msg.gsub("People","Número de Convidados") %>
          <% msg = msg.gsub("Event date","Data do evento") %>
          <% msg = msg.gsub("Event time","Início do evento") %>
          <% msg = msg.gsub("Erro","Ops!!") %>
          <% msg = msg.gsub("invalid date","Esta data não existe, digite um valor válido") %>
            <p class="span f18"><%= msg unless msg.include? "Password" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_form_success.html.erb
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content white-text">
          <span class="card-title green-text text-darken-2"><%= I18n.t("class.#{object.class.to_s.downcase}") %><%= " #{(object.created_at == object.updated_at) ? 'cadastrado' : 'atualizado'} com sucesso!" %></span>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_waver_bottom.html.erb
<div style="height: 150px; overflow: hidden; margin-top: <%= margin %> z-index: 3; position: absolute; width: 100%;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C125.27,-20.22 309.81,181.08 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: <%= color %>;"></path></svg></div>